version: '3'
services:
  db:
    image: "yobasystems/alpine-mariadb:10.4.13"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "data-db:/var/lib/mysql"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
    env_file:
      - ./.env
    networks:
      - servers
    restart: on-failure
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    ports:
      - 8084:3000
    env_file:
      - ./.env
    volumes:
      - "./src:/usr/src/server/src"
    networks:
      - servers
    restart: on-failure
networks:
  servers:
volumes:
  data-db:
